### ISSUE TITLE
SSL/TLS failure with requests and EPROTO response

### ISSUE THREAD

**Issue by Martii** [OpenUserJS/OpenUserJS.org#1323]
The following error has shown up just recently and is preventing some script uploads and the online editor from accepting scripts with a server trip:

``` sh-session
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO 140596207068992:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1500:SSL alert number 40
140596207068992:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

I'm in the process of rebuilding the current LTS *node* to see if that will help. That particular file is part of *node* and is beyond our control other than a rebuild to see if a VPS update broke the build.

* Restored SSL keys from November 2017 *(primary)* to be sure file corruption had not occurred. No change.
* Reinit project deps e.g. `rm node_modules` and `npm install`. No change
* New temporary project clone created. No Change
* Rolling back *node* to earlier version with *nvm* did **not** help.
* Rolling back to an older project clone did **not** help.
* Rebuilding *node*... No change
* Remove *nvm* completely... pending retest of system *node* recompile... .bashrc is new location instead of .profile.... difference in reinstallation merits removal, perhaps permanently.
* Test manual removal of https://github.com/OpenUserJS/OpenUserJS.org/blob/8d90bfa0e2e742dfcbeebb580785b3044cc98351/app.js#L247-L270 and use native *node* encryption handling. No change
* Test non-secure mode... FAIL... lovely... browser issue always kicking in https. Will followup with that later.

Outside ref(s):
* https://github.com/Martii/UserScripts/commit/5180c68cd12b902aa72fac2b637d85655c23d064 *(worked fine on this day with a GH import and a manual script edit on OUJS)*
* https://openuserjs.org/garage/Problems_pushing_scripts_from_Github#comment-161779f7995 *(Report)*

**Comment by Martii** [comment]
Cause Identified: Definitely *node* throwing an untrapped error and dealing with TLS.

Workaround: Remove icon request since https://confluence.bredex.de/images/icons/profilepics/default.png does this consistently so far.

Additional session failure using *request* on dev:

``` sh-session
events.js:183
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid status code: EPROTO
    at ServerResponse.writeHead (_http_server.js:190:11)
    at ServerResponse.writeHead (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:181:8)
    at ServerResponse.res.write (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/express-minify/index.js:88:14)
    at MuStream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at MuStream.emit (events.js:211:7)
    at next (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:49:16)
    at _render (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:96:3)
    at Object.render (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:15:10)
    at Immediate._onImmediate (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu.js:196:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Note: Since this routine needs to take a nap for a while... If I see an `@icon` larger than it is supposed to be the account is eligible for termination under the TOS. Just thought I'd do a reject instead of a termination. :\

**Comment by Martii** [comment]
Refs:
* nodejs/node#3692 *(Similar)*
* nodejs/node#16196 *(Similar)*
* Several others throughout a massive search.

**Comment by Martii** [comment]
If anyone has any suggestions on how to trap the TLS issue it would be appreciated... otherwise I'll keep looking when I have a moment.

**Comment by sizzlemctwizzle** [comment]
Without looking at any code, outgoing requests can fail for any number of reasons. From what the user said about requiring intranet authencation to access the icon, a failure is to be expected. The only problem was that an uncaught exception was generated as a result, and that cannot be allowed to happen under any circumstance. Any error that could possibly result from a request to an external server should be caught and logically treated as if we recieved a 404. I don't know if a TLS requires anything more than wrapping https.get in a try-catch (guessing at the solution based on the stack trace), but a connection error is a connection regardless of why.

**Comment by Martii** [comment]
> You need to use https.get(options, fn).on('error', fn)

We are *(were)* at https://github.com/OpenUserJS/OpenUserJS.org/pull/1324/files#diff-b755ddbc6b2edf964c5586d742e3afdaL1488 . This didn't trap it at all.

The simle request at https://github.com/OpenUserJS/OpenUserJS.org/pull/1324/files#diff-b755ddbc6b2edf964c5586d742e3afdaL1459
The data stream at https://github.com/OpenUserJS/OpenUserJS.org/pull/1324/files#diff-b755ddbc6b2edf964c5586d742e3afdaL1461
The end stream at https://github.com/OpenUserJS/OpenUserJS.org/pull/1324/files#diff-b755ddbc6b2edf964c5586d742e3afdaL1468
The error trap at https://github.com/OpenUserJS/OpenUserJS.org/pull/1324/files#diff-b755ddbc6b2edf964c5586d742e3afdaL1488

I'm trying a tls.connect *(assuming this it the right path)* to see if I can trap a double call to that problematic server using a lower level class function from *node*... not sure if this will work and is a 2nd chore.

**Comment by Martii** [comment]
@sizzlemctwizzle 

Yeah you came up with the same solution as @6-8-axnw1bom81v5xa3nh48c did now that I look into this way deep however we still get this on development:

``` sh -session
events.js:137
      throw er; // Unhandled 'error' event
      ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: EPROTO
    at ServerResponse.writeHead (_http_server.js:197:11)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:188:8)
    at ServerResponse.res.write (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/express-minify/index.js:88:14)
    at MuStream.ondata (internal/streams/legacy.js:16:26)
    at MuStream.emit (events.js:160:13)
    at next (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:49:16)
    at _render (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:96:3)
    at Object.render (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:15:10)
    at Immediate.<anonymous> (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu.js:196:16)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

using:

``` js
``` js
          fn = /^http:/.test(icon) ? http : https;
          fn.get(URL.parse(icon), function (aRes) {
            var chunks = [];
            aRes.on('data', function (aChunk) {
              var buf = null;
              chunks.push(aChunk);
              buf = Buffer.concat(chunks);
              if (buf.length > 3048) { // NOTE: KiB
                aRes.destroy();
              }
            }).on('end', function () {
              buffer = Buffer.concat(chunks);
              try {
                dimensions = sizeOf(buffer);
              } catch (aE) {
                aInnerCallback(new statusError({
                  message: '`@icon` ' + aE.message,
                  code: aE.code
                }));
                return;
              }

              if (!acceptedImage(dimensions)) {
                aInnerCallback(new statusError({
                  message: '`@icon` unsupported file type or dimensions are too large.',
                  code: 400
                }), null);
              } else {
                aInnerCallback(null);
              }
            }).on('error', function (aErr) { // Trap on response... also tested removed
              aInnerCallback(aErr);
            });
          }).on('error', function (aErr) { // Trap on request
              aInnerCallback(aErr);
          });
```
```

**Comment by Martii** [comment]
Ref:
* nodejs/help#1098

**Comment by Martii** [comment]
Additional related error using a bogus domain with http://s33333333333333333333333.amazonaws.com/uso_ss/icon/13701/large.png :

``` sh-session
events.js:137
      throw er; // Unhandled 'error' event
      ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: ENOTFOUND
    at ServerResponse.writeHead (_http_server.js:197:11)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:188:8)
    at ServerResponse.res.write (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/express-minify/index.js:88:14)
    at MuStream.ondata (internal/streams/legacy.js:16:26)
    at MuStream.emit (events.js:160:13)
    at next (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:49:16)
    at _render (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:96:3)
    at Object.render (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu/renderer.js:15:10)
    at Immediate.<anonymous> (/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/mu2/lib/mu.js:196:16)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

This means that http as well needs to continue to be resuspended since the `.on('error',...` *(current code point [here](https://github.com/OpenUserJS/OpenUserJS.org/blob/c4887850ccae25273644023aaa29d51fb26f2fa8/controllers/scriptStorage.js#L1517-L1519))* isn't picking up on this up either.

**Comment by Martii** [comment]
Closing for now... will reopen if the server trips again.
