### ISSUE TITLE
*passport-aol* failing

### ISSUE THREAD

**Issue by Martii** [OpenUserJS/OpenUserJS.org#1369]
``` console
InternalOpenIDError: Failed to discover OP endpoint URL  (message: No providers found for the given identifier)
    at ~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/passport-openid/lib/passport-openid/strategy.js:249:52
    at ~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/passport-openid/node_modules/openid/openid.js:787:14
    at ~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/passport-openid/node_modules/openid/openid.js:577:13
    at ~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/passport-openid/node_modules/openid/openid.js:533:11
    at Request._callback (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/passport-openid/node_modules/openid/openid.js:228:7)
    at Request.self.callback (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (~/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
```

Finally dug up my credentials for AOHell.... so anyhow. Dev and production return similar results.

Tried:
* *passport-steam*s fix at https://github.com/OpenUserJS/passport-aol/tree/OpenID
* *passport-openid-node6support*s fix at https://github.com/OpenUserJS/passport-aol/tree/OpenID2
* https://identity.aol.com/solutions/openid/ and https://identity.aol.com/solutions/openid/xrds for `providerURL`... no change

Nothing appears to work. I will attempt to dive into the source however OpenID based passports are usually highly unmaintained. I have observed *passport-yahoo* successfullly auth'ing however I would be willing to consider deprecating OpenID at some point if there aren't any responses from these packages. This includes *passport-steam* since they are OpenID as well.

**Comment by Martii** [comment]
Ref:
* Direct url test from [/jaredhanson/passport-aol/blob/`05a6346`/lib/passport-aol/strategy.js#L43](https://github.com/jaredhanson/passport-aol/blob/05a6346ba1659f689a85f092bbeaa700ef569894/lib/passport-aol/strategy.js#L43) returns:

```
Forbidden
You don't have permission to access /auth/openid/xrds on this server.
```

``` console
https://api.screenname.aol.com/auth/openid/xrds

GET /auth/openid/xrds HTTP/1.1
Host: api.screenname.aol.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 SeaMonkey/2.49.3
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

HTTP/1.1 403 Forbidden
Date: Mon, 21 May 2018 22:11:44 GMT
Server: ATS
Content-Length: 218
Content-Type: text/html; charset=iso-8859-1
Age: 0
Connection: close
Strict-Transport-Security: max-age=15552000
```

Testing corresponding url in *passport-yahoo* and *passport-steam* it returns a XML document.

**Comment by Martii** [comment]
Ref:

Re: [/jaredhanson/passport-aol/tree/`05a6346`/examples/signon](https://github.com/jaredhanson/passport-aol/tree/05a6346ba1659f689a85f092bbeaa700ef569894/examples/signon) after tweaking to newer express settings

1. http://localhost:3000
2. Logging in
3. Browser error of:
``` console
InternalOpenIDError: Failed to discover OP endpoint URL
    at ~/tmp/passport-aol/examples/signon/node_modules/passport-openid/lib/passport-openid/strategy.js:249:52
    at ~/tmp/passport-aol/examples/signon/node_modules/openid/openid.js:874:14
    at ~/tmp/passport-aol/examples/signon/node_modules/openid/openid.js:664:13
    at ~/tmp/passport-aol/examples/signon/node_modules/openid/openid.js:620:11
    at done (~/tmp/passport-aol/examples/signon/node_modules/openid/openid.js:258:9)
    at IncomingMessage.<anonymous> (~/tmp/passport-aol/examples/signon/node_modules/openid/openid.js:262:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

Same error and url forbidden as last comments.

**Comment by Martii** [comment]
Refs:
* https://meta.stackexchange.com/questions/308887/is-it-still-possible-to-log-into-stack-exchange-using-an-aol-openid ... similar issue to ours. Vague reference to a dupe in a reply that doesn't seem to be cited anywhere.
* https://meta.stackexchange.com/questions/307647/support-for-openid-ends-on-july-1-2018?noredirect=1 ... stack exchange is deprecating OpenID logins

**Comment by Martii** [comment]
So basically in summary `providerUrl` is returning forbidden... that to me indicates either AOL end of lifed OpenID or they have a misconfiguration of their service.

After I look into who is using AOL on OUJS I'm probably going to remove it as an auth altogether... I may even parse the DB and remove AOL auths altogether since not even existing users can get in due to this issue.... **UNLESS** someone can cite an aol domained document that says otherwise.

**Comment by Martii** [comment]
Few days back, and today, the url in the passport of url test from [/jaredhanson/passport-aol/blob/`05a6346`/lib/passport-aol/strategy.js#L43](https://github.com/jaredhanson/passport-aol/blob/05a6346ba1659f689a85f092bbeaa700ef569894/lib/passport-aol/strategy.js#L43) does this now:

``` console
HTTP ERROR 404

Problem accessing /auth/openid/xrds. Reason:

    Not Found

Powered by Jetty:// 9.4.z-SNAPSHOT
```

I think it's safe to presume it's dead and gone. Sure would have been nice if AOL would have made an announcement. This may have been terminated when AIM was.

Anyhow... still haven't decided what to do with those remaining accounts... will probably at least delete the ones that don't have any activity... the rest \*still pondering\*.

**Comment by Martii** [comment]
All but 8 orphaned standalone AOL accounts deleted... I'd kind of like to keep their content around for Copyright validation... still pondering...

**Comment by Martii** [comment]
... ponder complete... should keep them around. They are minimal in quantity and good for a unit test case. Closing.
