### ISSUE TITLE
Migrate from MongoDB 4.x to 5.x

### ISSUE THREAD

**Issue by Martii** [OpenUserJS/OpenUserJS.org#1825]
1. Check with backend to make sure VPS is supported *(hopefully)*
2. Take OUJS offline
3. Compact DB
4. Backup existing pro DB *(ex. `mongodump --gzip --db openuserjs_devel --archive=./dev/devDBdirty.gz` but productions)*
5. Purge 4.x
6. Target new sources
7. Install 5.x *(may need db tools from .deb package... local installation was a bit weird with `apt`)*
8. Import pro DB *(ex. `mongorestore --gzip --db openuserjs_devel --archive=./dev/devDBdirty.gz` but productions)*
9. Put OUJS online *(possible in read only mode just for initial checking)*

NOTE(S)
* `mongo` command is deprecated for `mongosh`
* Time it took locally was about 1 hour ... so approximately 1 hour downtime. Schedule at some point with notice on OUJS.

**Comment by Martii** [comment]
This is starting to get important. `mongo` is starting to show bitrot as an updated element didn't update but it said it did. Need `mongosh` soon as it is more actively developed. Blehh.... more work for the new year as usual.

See also:
* https://github.com/OpenUserJS/OpenUserJS.org/pull/1899#issuecomment-1000253046

**Comment by Martii** [comment]
Interesting:

* https://docs.mongodb.com/manual/core/index-multikey/

MongoDB 4.x seems to allow one only on production however local dev here says the index was created when I did **2**. Since pro is a slightly different platform may not work with 2... but now there is an option. Been waiting for this feature for several years now. We can query multiple "parallel arrays" for years however we can't index them is what they are saying in the docs... paraphrased of course.

**Comment by Martii** [comment]
Misc critical error encountered:

``` console
MongoDB Script save critical error
iFelix18/Monkey_Utils.js
{
 "version": 0,
 "modifiedPaths": [
  "meta",
  "uses",
  "hash",
  "updated"
 ]
}
0bc2e3b4-803a-11ec-868a-26da9250a6e2 statusError: {
 "message": "Database write error",
 "code": 502
}
    at ~/OpenUserJS.org1/controllers/scriptStorage.js:2178:27
    at ~/OpenUserJS.org1/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  status: { message: 'Database write error', code: 502 },
  code: undefined
}
```

No further updates to *mongoose* and *mongodb* at this time.

Could be related to https://stackoverflow.com/questions/70536836/unreachable-mongodb-once-memory-is-being-allocated-on-the-swap since that's what came up on a log investigation. User is sending both normal and minified scripts from GH to OUJS.

**Comment by Martii** [comment]
This is [now scheduled](https://openuserjs.org/announcements/Server_Maintenance?p=2#comment-184cc68c762) to happen with the next 96 hours. I'm quite busy off and on but will find some time for this.

**Comment by Martii** [comment]
Thrills: Cc: @sizzlemctwizzle 

> Callbacks are deprecated in the Node.js driver version 4.10 and will be removed in a future release. We recommend that you use Promises or Async/Await instead.
>
> If your application requires the use of callbacks, you can use the [MongoDB Node.js driver with optional callback support](https://www.npmjs.com/package/mongodb-legacy)
, which wraps the Node.js driver and provides optional callback support.

Ref: https://www.mongodb.com/docs/drivers/node/current/fundamentals/promises/#callbacks--deprecated-

Pretty sure they are already eol'd as I'm getting `MongoInvalidArgumentError: Argument "options" must not be function` when used with sessions in the *mongodb*@4.x driver. This also leads heavily into #1556

Anyhow... in-place migration from MongoDB 4.x to MongoDB 6.x failed... but luckily purged it as I described above and restored. Seems to be working just like dev station.

Closing this migration issue.
