### ISSUE TITLE
Discover what is breaking binary based packages on some dev/pro machines

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#441]
Since this is specific currently to @Zren but can apply to others if they are having any issue with their system... only those having issues need apply themselves.

Please post results of the following:
- Platform with full version information e.g. if Windows which one.. if Linux which one... if Mac OSX which one
- `$ npm -v`
- `$ node -v`
- `$ npm install express-minify`
- Any other useful information

See related:
- sass/node-sass#517

**Comment by Martii** [comment]
@Zren 
Are you still getting this? The only error I get on pro is that a SunOS binary isn't available to be downloaded but it has made zero difference on production running... plus we don't use SASS currently even in *express-minify* e.g. it installs here locally on my devs, installs on pro and I tested your site out with [a specific request](https://oujs.herokuapp.com/css/common.css) and it is minifying CSS so *express-minify* appears to not be the culprit for you.

**Comment by Martii** [comment]
Misc ref:
* https://github.com/kcbanner/connect-mongo/issues/194#issuecomment-144312827 with kerberos via *connect-mongo* ERR on Linux boxes...  install the OS dep with whatever package manager you use:
Example:
``` sh-session
$ sudo apt-get install libkrb5-dev
```
... this will flip the ERR in gyp to nothing or just warnings. Some 64 bit distros require `lib64krb5-devel` e.g. install the developer library not just the runtime library. This ERR is non-fatal on Linux boxes but kind of disrupting to see.

From this *(clipped)*:
``` sh-session
$ npm install

> kerberos@0.0.17 install /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.53-nrj-desktop-1rosa-x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> kerberos@0.0.17 install /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.53-nrj-desktop-1rosa-x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> OpenUserJS.org@0.2.1 postinstall /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org
> node dev/init.js

Checking project dependencies. Please wait...
```
... to this *(clipped)*:

``` sh-session
$ npm install

> kerberos@0.0.17 install /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:362:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:930:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org/node_modules/kerberos/build'

> OpenUserJS.org@0.2.1 postinstall /home/user/repo/git/OpenUserJS.org/martii/OpenUserJS.org
> node dev/init.js

Checking project dependencies. Please wait...
```

**Comment by Martii** [comment]
Closing as stale
